### ISSUE TITLE
New npm package?

### ISSUE THREAD

**Issue by dhendo** [clarkf/minifyjs#6]
Hi Clark, can you publish a new npm package version to reflect the beautify changes?

**Comment by clarkf** [comment]
Just pushed package. New version is `v0.2.0`.
Just a note though that the binary (https://github.com/clarkf/minifyjs/blob/v0.2.0/bin/minify) is not fully error-free currently. There's a strange bug where, when piping from STDIN to a non-js engine, there's a good chance you'll get an `EPIPE error`. I will work on this for 0.2.1.
